baseURL = "http://localhost"
title = "MSI DN2"

[params]
  dateform = "Jan 2, 2006"
  themeColor = "#494f5c"

[menu]
  [[menu.main]]
    name = "Show Date (wait for db to initialize)"
    url = "/date/date.html"
    weight = 10
