version: '3'

services:

#  web:
#    build: website
#    volumes:
#      - date-volume:/usr/share/nginx/html/date/
#    ports:
#      - "9999:80" # debugging
#    networks:
#      - web-network
#    labels:
#      - "traefik.enable=true"
#      - "traefik.backend=web"
#     - "traefik.docker.network=web-network"
#      - "traefik.port=80"
#      - "traefik.frontent.rule=Host:10.145.106.252"

#  clock:
#    build: clock
#    volumes:
#      - date-volume:/date/

  proxy:
    image: traefik:alpine
    command: --api.insecure=true --providers=docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - web-network

#volumes:
#  date-volume:

#networks:
#  web-network: