version: '2'

services:

  web:
    build: website
    ports:
      - "8080:80"
    volumes:
      - date:/usr/share/nginx/html/date

  clock:
    build: clock
    volumes:
      - date:/date

volumes:
  date: