version: '3.1'

services:

  # Ni volume-a ker za potrebe te naloge ne rabimo shraniti vsebine baze
  db:
    image: mysql
    container_name: database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
       - MYSQL_USER=mysql
       - MYSQL_PASSWORD=password
       - MYSQL_ROOT_PASSWORD=password
       - MYSQL_DATABASE=time
       - MYSQL_INITDB_SKIP_TZINFO
    networks:
      - db-net
    labels:
      - "traefik.enable=false"

  web:
    build: website
    container_name: website
    restart: always
    volumes:
      - date-volume:/usr/share/nginx/html/date/
    labels:
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"

  proxy:
    image: traefik:v2.3
    container_name: proxy
    restart: always
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  clock:
    build: clock
    restart: always
    container_name: clock
    volumes:
      - date-volume:/date/
    networks:
      - db-net
    labels:
      - "traefik.enable=false"

volumes:
  date-volume:

networks:
  db-net:
    driver: bridge