version: '2'

services:

  web:
    build: website
    ports:
      - "8080:80"
    volumes:
      - ./temp:/usr/share/nginx/html

#  clock:
#    build: clock
#    volumes:
#      - date:/date

#volumes:
#  date: