version: '3'

services:

  web:
    build: website
    volumes:
      - date-volume:/usr/share/nginx/html/date/
    labels:
      - "traefik.http.routers.web.rule=Host(`localhost`)"

  clock:
    build: clock
    volumes:
      - date-volume:/date/

  proxy:
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  date-volume: